# Generated by Django 5.2.7 on 2025-11-05 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism_spots', '0002_touristspot_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='touristspot',
            name='image',
        ),
        migrations.CreateModel(
            name='TouristSpotImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tourist_spots/')),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tourism_spots.touristspot')),
            ],
        ),
    ]
