# Generated by Django 5.2.7 on 2025-11-13 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism_spots', '0003_remove_touristspot_image_touristspotimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristspot',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
